# Generated by Django 2.0.3 on 2018-03-23 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geboortedatum', models.DateField(blank=True, null=True)),
                ('rol', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Deel van de Gemeenschap'), (2, 'Derden')], null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='resources/assets/images/avatars/')),
                ('gebruiker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
