# Generated by Django 2.0.3 on 2018-03-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresboek', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adres',
            name='bevestigd',
        ),
        migrations.AddField(
            model_name='adres',
            name='toevoeging',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
