# Generated by Django 2.0.3 on 2018-03-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresboek', '0002_auto_20180315_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='locatie_foto',
            field=models.ImageField(blank=True, null=True, upload_to='../recources/assets/images/locatie_fotos/'),
        ),
    ]
