# Generated by Django 2.0.3 on 2018-03-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresboek', '0003_adres_locatie_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='in_de_wijk',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adres',
            name='locatie_foto',
            field=models.ImageField(blank=True, null=True, upload_to='recourses/images/locatie_fotos/'),
        ),
    ]
