# Generated by Django 2.0.3 on 2018-03-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresboek', '0004_auto_20180316_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='vernomen_adres',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='adres',
            name='in_de_wijk',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='adres',
            name='locatie_foto',
            field=models.ImageField(blank=True, null=True, upload_to='resources/images/locatie_fotos/'),
        ),
    ]
