# Generated by Django 2.0.3 on 2018-03-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresboek', '0005_auto_20180317_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='locatie_foto',
            field=models.ImageField(blank=True, null=True, upload_to='resources/assets/images/locatie_fotos/'),
        ),
    ]
