# Generated by Django 2.0.3 on 2018-03-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresboek', '0006_auto_20180318_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='breedtegraad',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='adres',
            name='lengtegraad',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='breedtegraad',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='lengtegraad',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True),
        ),
    ]
