# Generated by Django 2.0.3 on 2018-03-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adresboek', '0007_auto_20180318_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adres',
            name='breedtegraad',
        ),
        migrations.RemoveField(
            model_name='adres',
            name='lengtegraad',
        ),
        migrations.RemoveField(
            model_name='postcode',
            name='breedtegraad',
        ),
        migrations.RemoveField(
            model_name='postcode',
            name='lengtegraad',
        ),
    ]
