# Generated by Django 2.0.3 on 2018-03-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresboek', '0008_auto_20180318_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
