# Generated by Django 2.0.3 on 2018-03-19 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adresboek', '0009_auto_20180319_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='slug',
            field=models.CharField(default=uuid.uuid4, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='adres',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
