# Generated by Django 2.0.3 on 2018-03-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresboek', '0010_auto_20180319_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='huisnummer',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adres',
            name='toevoeging',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='adres',
            name='vernomen_adres',
            field=models.CharField(blank=True, default='Onbekend', max_length=100),
        ),
        migrations.AlterField(
            model_name='adres',
            name='vernomen_bewoners',
            field=models.CharField(blank=True, default='Onbekend', max_length=100),
        ),
    ]
