# Generated by Django 2.0.3 on 2018-03-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresboek', '0011_auto_20180319_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='huisnummer',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
