# Generated by Django 2.0.3 on 2018-03-19 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresboek', '0013_auto_20180319_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='postcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adresboek.Postcode'),
        ),
    ]
